# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

before_install:
  - sudo rm -rf /etc/apt/sources.list.d/*
  - sudo add-apt-repository -y ppa:pypy/ppa
  - wget -O- http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
  - echo deb http://packages.couchbase.com/ubuntu precise precise/main | sudo tee /etc/apt/sources.list.d/couchbase.list
  - sudo apt-get update
  - sudo apt-cache search libcouchbase
  # - sudo apt-get install libxml2-dev libxslt-dev python-all-dev libffi6 libffi-dev 
  # - sudo apt-get install build-essential libssl-dev python-openssl

install:
  - sudo apt-get -y install libcouchbase-dev libcouchbase2-core #libcouchbase2-libevent libevent-dev python-gevent
  # - pip -q install gevent || echo "Couldn't find gevent"
  # - pip -q install twisted
  # - pip -q install testresources
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: 
  - cd couchbase-python-cffi
  # - export CFLAGS=-Qunused-arguments
  # - export CPPFLAGS=-Qunused-arguments
  # - python setup.py test  
  # - python setup.py build
  - python setup.py install
  - cd ..
  - python runtests.py
